### ISSUE TITLE
possible to show "hide/show tasks(or blocks, at least) scheduled > today"?

### ISSUE THREAD

**Issue by Simeonh2021** [mlanza/logseq-style-carousel#2]
Can carousel or wide eyed make it possible to show "hide/show tasks(or blocks, at least) scheduled > today"? Many thanks!

**Comment by mlanza** [comment]
Carousel operates off what can be seen in the DOM itself and applies CSS rules.  Unfortunately, there is no discern future tasks from the DOM using CSS rules as Logseq currently renders it; however, your request is a picture perfect candidate for why I [proposed a plugin rendering pipeline](https://discuss.logseq.com/t/add-plugin-rendering-pipeline/5549). Please consider voting for it.  

With this proposed feature, future tasks could be easily identified and enrichment attributes (e.g. a "future" class) could be rendered to a block's DOM element.  This would make it easy for Carousel or some other plugin to hide future tasks.  But, lacking this feature, Carousel is not up to the task.

Now it may be possible to update Wide Eyed to handle what you propose.

**Comment by Simeonh2021** [comment]
> Carousel operates off what can be seen in the DOM itself and applies CSS rules. Unfortunately, there's no way to discern future tasks from the DOM using CSS rules as Logseq currently renders it; however, your request is a picture perfect candidate for why I [proposed a plugin rendering pipeline](https://discuss.logseq.com/t/add-plugin-rendering-pipeline/5549). Please consider voting for it.
> 
> With this proposed feature, future tasks could be easily identified and enrichment attributes (e.g. a "future" class) could be rendered to a block's DOM element. This would make it easy for Carousel or some other plugin to hide future tasks. But, lacking this feature, Carousel is not up to the task.
> 
> Now it may be possible to update Wide Eyed to handle what you propose.

Thank you. Looking forward to your update!

**Comment by mlanza** [comment]
Upon further consideration, I integrated the features of Wide Eyed into Style Carousel.  For the reasons explained in the [README](https://github.com/mlanza/logseq-style-carousel#readme) you may want to install it locally.

I also demonstrate a configuration in the README (see "futures" in the sample settings) for doing exactly what you ask.
