### ISSUE TITLE
About the cross origin

### ISSUE THREAD

**Issue by haydenull** [mlanza/logseq-style-carousel#4]
I've also come across a cross origin [issue](https://github.com/haydenull/logseq-plugin-agenda/issues/14).

Maybe you can try my solution: Set effect to true, so that logseq loads the plugin with the file protocol.

https://github.com/logseq/marketplace/pull/122

**Comment by mlanza** [comment]
Thank you, @haydenull.  I've created a pull request.  I'll let you know how it works out.

**Comment by mlanza** [comment]
@haydenull — I appreciate your taking the time to share this.  It appears to have solve my issue.
