### ISSUE TITLE
Broken since logseq 0.66?

### ISSUE THREAD

**Issue by Simeonh2021** [mlanza/logseq-style-carousel#5]
Since logseq 0.66, only "hiding done task"feature works.  Hiding "future"and"block properties" no longer works. 

Would you check it out? Many thanks.

osx 12.3.1, 0.66 nightly 220426

**Comment by mlanza** [comment]
Please include your complete plugin settings file and I'll look.

**Comment by Simeonh2021** [comment]
> Please include your complete plugin settings file and I'll look.

{
  "disabled": false,
  "buttons": {
    "todos": {
      "desc": "Toggles the visibility of closed tasks",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without closed tasks",
          "char": "\\ecf0",
          "hits": "div#main-content-container div[data-refs-self*='\"done\"'], div#main-content-container div[data-refs-self*='\"canceled\"']",
          "style": "div[data-refs-self*='\"done\"']:not(:focus-within), div[data-refs-self*='\"canceled\"']:not(:focus-within) {display: none;}"
        },
        {
          "tooltip": "With closed tasks",
          "char": "\\ea9a",
          "hits": "div#main-content-container div[data-refs-self*='\"done\"'], div#main-content-container div[data-refs-self*='\"canceled\"']",
          "style": "div#main-content-container:hover div[data-refs-self*='\"done\"'] span.inline, div#main-content-container:hover div[data-refs-self*='\"canceled\"'] span.inline {text-decoration: underline wavy;}"
        }
      ]
    },
    "futures": {
      "desc": "Toggles the visibility of future tasks",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without future tasks",
          "char": "\\eb3e",
          "query": "[:find (pull ?block [*]) :in $ ?start ?end :where (?block :block/scheduled ?d) [(> ?d ?start)] [(< ?d ?end)]]",
          "inputs": [
            "today 0",
            "today 10000"
          ],
          "matches": [],
          "hit": "div[blockid=\"@uuid\"]",
          "rules": "{display: none;}"
        },
        {
          "tooltip": "With future tasks",
          "char": "\\eb3f",
          "query": "[:find (pull ?block [*]) :in $ ?start ?end :where (?block :block/scheduled ?d) [(> ?d ?start)] [(< ?d ?end)]]",
          "inputs": [
            "today 0",
            "today 10000"
          ],
          "matches": [],
          "hit": "div[blockid=\"@uuid\"]",
          "selector": "div#main-content-container:hover div[blockid=\"@uuid\"]",
          "rules": "{text-decoration: underline wavy;}"
        }
      ]
    },
    "props": {
      "desc": "Toggles the visibility of page properties",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without page properties",
          "char": "\\eeaf",
          "hits": ".pre-block",
          "style": ".pre-block {display: none}"
        },
        {
          "tooltip": "With page properties",
          "char": "\\eeb0",
          "hits": ".pre-block",
          "style": "div#main-content-container:hover .pre-block {text-decoration: underline wavy;}"
        }
      ]
    },
    "boardgames": {
      "desc": "Indicates a favorite pastime appears on the page.",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Boardgames!",
          "char": "\\eb66",
          "hits": "div#main-content-container div[data-refs-self*='\"boardgame\"'], div#main-content-container div[data-refs-self*='\"boardgames\"']",
          "style": "div#main-content-container:hover div[data-refs-self*='\"boardgame\"'] span.inline, div#main-content-container:hover div[data-refs-self*='\"boardgames\"'] span.inline {background-color: lightyellow;}"
        }
      ]
    }
  }
}


> Please include your complete plugin settings file and I'll look.

{
  "disabled": false,
  "buttons": {
    "todos": {
      "desc": "Toggles the visibility of closed tasks",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without closed tasks",
          "char": "\\ecf0",
          "hits": "div#main-content-container div[data-refs-self*='\"done\"'], div#main-content-container div[data-refs-self*='\"canceled\"']",
          "style": "div[data-refs-self*='\"done\"']:not(:focus-within), div[data-refs-self*='\"canceled\"']:not(:focus-within) {display: none;}"
        },
        {
          "tooltip": "With closed tasks",
          "char": "\\ea9a",
          "hits": "div#main-content-container div[data-refs-self*='\"done\"'], div#main-content-container div[data-refs-self*='\"canceled\"']",
          "style": "div#main-content-container:hover div[data-refs-self*='\"done\"'] span.inline, div#main-content-container:hover div[data-refs-self*='\"canceled\"'] span.inline {text-decoration: underline wavy;}"
        }
      ]
    },
    "futures": {
      "desc": "Toggles the visibility of future tasks",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without future tasks",
          "char": "\\eb3e",
          "query": "[:find (pull ?block [*]) :in $ ?start ?end :where (?block :block/scheduled ?d) [(> ?d ?start)] [(< ?d ?end)]]",
          "inputs": [
            "today 0",
            "today 10000"
          ],
          "matches": [],
          "hit": "div[blockid=\"@uuid\"]",
          "rules": "{display: none;}"
        },
        {
          "tooltip": "With future tasks",
          "char": "\\eb3f",
          "query": "[:find (pull ?block [*]) :in $ ?start ?end :where (?block :block/scheduled ?d) [(> ?d ?start)] [(< ?d ?end)]]",
          "inputs": [
            "today 0",
            "today 10000"
          ],
          "matches": [],
          "hit": "div[blockid=\"@uuid\"]",
          "selector": "div#main-content-container:hover div[blockid=\"@uuid\"]",
          "rules": "{text-decoration: underline wavy;}"
        }
      ]
    },
    "props": {
      "desc": "Toggles the visibility of page properties",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Without page properties",
          "char": "\\eeaf",
          "hits": ".pre-block",
          "style": ".pre-block {display: none}"
        },
        {
          "tooltip": "With page properties",
          "char": "\\eeb0",
          "hits": ".pre-block",
          "style": "div#main-content-container:hover .pre-block {text-decoration: underline wavy;}"
        }
      ]
    },
    "boardgames": {
      "desc": "Indicates a favorite pastime appears on the page.",
      "refreshRate": 5,
      "hits": [
        "text-decoration: underline;",
        ""
      ],
      "styles": [
        {
          "tooltip": "Boardgames!",
          "char": "\\eb66",
          "hits": "div#main-content-container div[data-refs-self*='\"boardgame\"'], div#main-content-container div[data-refs-self*='\"boardgames\"']",
          "style": "div#main-content-container:hover div[data-refs-self*='\"boardgame\"'] span.inline, div#main-content-container:hover div[data-refs-self*='\"boardgames\"'] span.inline {background-color: lightyellow;}"
        }
      ]
    }
  }
}

**Comment by Simeonh2021** [comment]
Hi, mlanza. I've updated to 0.67 nightly 220502(most updated so far). The issue remains. I've made some screenshots of my json. Would you help me check it？Many thanks . 

![Pasted Graphic](https://user-images.githubusercontent.com/90461274/166679450-1426d628-0cdc-470b-8fb8-812f8a139eca.png)
![l E ieart tene fooene KPtere Fiensebeaea To N foarai dle N feme1](https://user-images.githubusercontent.com/90461274/166679469-9911a9ff-0d9d-45cd-a839-32924e47712f.png)
![Pasted Graphic 2](https://user-images.githubusercontent.com/90461274/166679490-e9926479-038d-44e7-847e-d80393641709.png)

**Comment by Simeonh2021** [comment]
By the way, I've copied and pasted the content you've written for me in another reply. Sadly, the issue still remains (only hiding "done" tasks workds).

**Comment by mlanza** [comment]
I am unable to reproduce any issues and I've tested on both Mac and Windows.  I too have the latest Logseq.  Can you illustrate the problem on a Logseq page using screenshots?  Tell me what you're doing and what you're expecting to happen which is not happening.

**Comment by Simeonh2021** [comment]
> I am unable to reproduce any issues and I've tested on both Mac and Windows. I too have the latest Logseq. Can you illustrate the problem on a Logseq page using screenshots? Tell me what you're doing and what you're expecting to happen which is not happening.

https://user-images.githubusercontent.com/90461274/166897473-8cd83e9e-fa9a-4e31-9a71-85b848668f24.mov

**Comment by Simeonh2021** [comment]
> I am unable to reproduce any issues and I've tested on both Mac and Windows. I too have the latest Logseq. Can you illustrate the problem on a Logseq page using screenshots? Tell me what you're doing and what you're expecting to happen which is not happening.

Sure. See if this screenshot helps. Thanks. 

https://user-images.githubusercontent.com/90461274/166898239-f269058e-e9a3-40c8-885d-03cfce71dfb8.mov

**Comment by mlanza** [comment]
Thanks for the video.  Pull the latest update and make sure to update your plugin settings with the format now shown in the updated [README](https://github.com/mlanza/logseq-style-carousel#readme).  Use the latest Logseq.  Please let me know if we've made progress.

**Comment by mlanza** [comment]
Heads up.  I am extracting the queries feature into a separate plugin.  You may wish to await this fix before attempting to fix your situation.

**Comment by mlanza** [comment]
The queries feature has been extracted to [Classy plugin](https://github.com/mlanza/logseq-classy).

**Comment by Simeonh2021** [comment]
> Thanks for the video. Pull the latest update and make sure to update your plugin settings with the format now shown in the updated [README](https://github.com/mlanza/logseq-style-carousel#readme). Use the latest Logseq. Please let me know if we've made progress.

All works fine now! I'm also using Classy as well. Very nice!
