### ISSUE TITLE
classy and carousel not working again after 0.71?

### ISSUE THREAD

**Issue by Simeonh2021** [mlanza/logseq-style-carousel#7]
Hi mlanza, it seems carousel and classy stops working again after 0.71 and all nightly versions? Would you check if you have the same problem?

**Comment by mlanza** [comment]
I just installed 0.7.2.  Everything is working fine on my Mac.  I haven't tried Windows yet, but I'm expecting the same.

FYI.  I am no longer pursuing the cutting edge myself.  I love Logseq, but most of the changes I read in the change logs are not groundbreaking and few enhancements add anything to the work I'm doing.  If the releases were more impressive I might feel compelled to keep up, but they're pretty ordinary.  If pursuing the cutting edge is causing unnecessary breakage, it might be better to linger behind.

**Comment by Simeonh2021** [comment]
> I just installed 0.7.2. Everything is working fine on my Mac. I haven't tried Windows yet, but I'm expecting the same.
> 
> FYI. I am no longer pursuing the cutting edge myself. I love Logseq, but most of the changes I read in the change logs are not groundbreaking and few enhancements add anything to the work I'm doing. If the releases were more impressive I might feel compelled to keep up, but they're pretty ordinary. If pursuing the cutting edge is causing unnecessary breakage, it might be better to linger behind.

good insight. I will pick up next stable version and stay there until any significant update is issued.

**Comment by mlanza** [comment]
I just updated my Windows Logseq to 0.7.2 and it's working normally.  One thing you can try when you believe you're experiencing issues is open up the Developer Tools (CTRL+SHIFT+I) and see if the plugins are throwing any errors.  If they're breaking it will be made obvious there.  That's not to say there couldn't be silent errors, but it will rule out the obvious ones.
