### ISSUE TITLE
Can't use font icons

### ISSUE THREAD

**Issue by gioknx** [mlanza/logseq-style-carousel#9]
Hello! I love your plugin, and i'm trying to customize it with custom buttons (and icons).

I've used Character Map and looked up the code associated to the icon I want (in tabler fonts family),

 but most icons won't work and will just appear blank.
 
 Only a few icons work, and I've realized that the ones that work has 2 codes associated on Character Map.
 
 I.E.: "char": "\\f29e", wil give me blank instead of the actual char

 Am I doing something wrong?
  Thank you!

**Comment by mlanza** [comment]
Two slashes:

"\\f29e"

**Comment by gioknx** [comment]
Sorry, the single slash was actually a typo I've made when writing to here.

It does not work with 2 slashes too :( actually, there are a few icons that do, like 1% of them I think

![image](https://user-images.githubusercontent.com/6156710/188014907-a37c1754-2850-4b5f-81d0-3c1670ef9c13.png)

**Comment by mlanza** [comment]
I looked up the character codes using Character Map on Windows.  I haven't found an equivalent program for my Mac.  But every icon I identify and every code I've tried so far has worked.  Or to put it another way, if you can get one code to work, you're just choosing a different pick from the lot.  So if one works and you change it and it doesn't work it's got nothing to do with the plugin.  Not sure what to tell but to try some other codes.
